### ISSUE TITLE
Remove action Format classes

### ISSUE THREAD

**Issue by yasuhito** [trema/pio#253]
**OpenFlow1.0**

- [x] [SendOutPort](https://github.com/trema/pio/blob/develop/features/open_flow10/send_out_port.feature)
- [x] [SetVlanVid](https://github.com/trema/pio/blob/develop/features/open_flow10/set_vlan_vid.feature)
- [x] [SetVlanPriority](https://github.com/trema/pio/blob/develop/features/open_flow10/set_vlan_priority.feature)
- [x] [StripVlanHeader](https://github.com/trema/pio/blob/develop/features/open_flow10/strip_vlan_header.feature)
- [x] [SetEtherSourceAddress](https://github.com/trema/pio/blob/develop/features/open_flow10/set_ether_source_address.feature)
- [x] [SetEtherDestinationAddress](https://github.com/trema/pio/blob/develop/features/open_flow10/set_ether_destination_address.feature) 
- [x] [SetIpSourceAddress](https://github.com/trema/pio/blob/develop/features/open_flow10/set_ip_source_address.feature)
- [x] [SetIpDestinationAddress](https://github.com/trema/pio/blob/develop/features/open_flow10/set_ip_destination_address.feature)
- [x] [SetIpTos](https://github.com/trema/pio/blob/develop/features/open_flow10/set_ip_tos.feature)
- [x] [SetTransportSourcePort](https://github.com/trema/pio/blob/develop/features/open_flow10/set_transport_source_port.feature)
- [x] [SetTransportDestinationPort](https://github.com/trema/pio/blob/develop/features/open_flow10/set_transport_destination_port.feature)
- [x] [Enqueue](https://github.com/trema/pio/blob/develop/features/open_flow10/enqueue.feature)

**OpenFlow1.3**
- [x] [SendOutPort](https://github.com/trema/pio/blob/develop/features/open_flow13/send_out_port.feature)
