### ISSUE TITLE
WIP: Pio::Dhcp修正

### ISSUE THREAD

**Issue by shun159** [trema/pio#77]
https://github.com/trema/pio/pull/65#issue-30931747
での新仕様検討をここで行いますので、こちらに転記します。

更新ごとにつらつらと書いていきます。
@yasuhito 何かありましたら追記をお願いします。
### 仕様の検討
- [x] テストの方針決め
  - [X] 生成のテスト
  - [X] 解析のテスト
  - [x] オプションのテスト
- [x] メソッドを自動生成する方法を考える
  - [X] 解析結果取得の為のメソッド生成
  - [x] 生成するときにハッシュを生成するメソッド生成
- [x] `.new`であたえられるオプションの種類の決定
- [x] メッセージ別のＴＬＶ値の明確化（end_of_tlvも含めすべて）
- [x] パーズした後に利用できるメソッドの種類の決定
- [x] デフォルト値についての決定
- [ ] DHCPリレーメッセージの仕様検討

### テストケース作成
- [ ] 解析テスト
  - [x] クライアントメッセージ
  - [ ] サーバーメッセージ
- [x] 生成テスト
  - [x] クライアントメッセージ
  - [x] サーバーメッセージ
- [ ] オプションテスト
  - [x] クライアントメッセージ
  - [ ] サーバーメッセージ
- [ ] 互換性テスト
  - [ ] いろいろなパケットの収集

### yardドキュメント追加
- [ ] 日本語ドキュメント
- [ ] 上記の英訳

### 既存の指摘点の対応について：  
- [x] Delete `_hash' from *_hash methods (#60)
- [x] Make private methods private (#64)
- [x] Rename `*_hash` methods to `*_tlv` (#63)
- [x] BootRequestOptions => BootRequest::Options (#53)
- [x] Remove the redundant `Dhcp` prefix from Dhcp::DhcpField (#52)
- [x] Refactor DHCP specs using rspec_given (#39)

## 関連RFC
http://www.zytrax.com/books/dhcp/apc/

## 方針：
- 既存のコードやＡＰＩは流用する（可能な限り）
- RFC2131(http://srgia.com/docs/rfc2131j.html)   に準拠する（できるだけ）  
- RFC2132(http://tools.ietf.org/html/rfc2132)  に基づく値のチェック
  - もし与えられたオプション値がこれに従っていない場合はraise等する。（厳密化）

#### ブロードキャストとユニキャストの使用
- ユニキャスト：
  - DHCP サーバーのアドレスを知っている場合、クライアントは DHCPDISCOVER や DHCPREQUEST で IP ブロードキャストアドレスではなく、そのユニキャストアドレスを使用しても良い。
  - クライアントはサーバーに DHCPRELEASE メッセージをユニキャストする
  - 既知の DHCP サーバーに DHCPINFORM メッセージを送信する場合にも、クライアントはユニキャストを使用しても良い。

- ブロードキャスト：
  - DHCPサーバのアドレスを知らない限り、ＤＨＣＰクライアントは、DHCPDISCOVER、DHCPREQUEST、DHCPINRFORM の各メッセージをブロードキャストする
  - クライアントがサーバーによって提供された IP アドレスを使用を拒否するなら、クライアントは DHCPDECLINE メッセージをブロードキャストする。 

#### ブロードキャストとユニキャストの使用
- Offer
送信先アドレスはユニキャストとブロードキャストが選択可能。
- Ack
送信先アドレスはユニキャストとブロードキャストが選択可能。
- Nack
送信先アドレスはブロードキャストアドレスに限定。

### DHCPリレーエージェントの振る舞いについて
http://www.cisco.com/cisco/web/support/JP/100/1007/1007781_100-j.html#dhcprfcref
を参考にする。
## 質問事項
- message.rbとかで書いている、`def_delegators`が`packet_in`が提供するメソッドとかぶっています。必要ですか？
> > 得られる情報が同じものをPioで提供する必要があるかと考えてます。
> > たとえば、packet_in.macsaと@frame.source_macって得られる情報同じです。
> 
> たぶん心配しているのは、`Trema::PacketIn` と Pio でコードの重複が出ないかということだと思いますが、`Trema::PacketIn` の各メソッドは Pio の各クラスのメソッドを呼ぶだけという実装になるので、コードの重複は出ないはずです。
> 
> たとえば `packet_in.macsa` は実装上は Pio の `dhcp.macsa` を呼ぶだけなので、Pio の `#macsa` はどっちみち必要です。
> 
> 
> > なので、Trema::PacketInから得られないL7とかのペイロード情報を提供するに
> > しておけば、如何かと。
> 
> こちらも、もしそういうメソッドがあれば `PacketIn` から参照できるようにしようと思っています。

- テスト方針について：これまでジェネレータが出したフレームでテストを書くことがありましたが、今回は実際にスニファしたデータをベースにテストを作成したいと考えています。そのため、テストコードからはどのオプションがmandatoryかoptionalかわからなくなるかもしれませんが、その辺ドキュメントすればいいかなと思います。また、そういった場合、最小限・最大のオプションそれぞれのテストをどうしようか、言ったところはありますが、ご意見・ご指摘お願いします。
> テストコードの書きかたで mandatory/optional も表現できるので、コードと分離したドキュメンテーションはいらないはずです。たとえば Arp のテストでやっているように、
> 
>     mandatory なオプションを指定しなかったら例外が上がる
>     optional なやつを指定しなかったらデフォルトになる
> 
> と書けばよいわけで、こうしておけば rspec -fs の実行結果がオプションのドキュメントになります。RSpec > はテストコードを仕様 (spec) として読めるようにという目的のツールなので、こういう使いかたをしましょう。

- dhcpのtlvデータを読み込むためのメソッドを自動生成などして、行数をうまいこと減らしたいです
````ruby
      def message_type
        get_tlv_field(Dhcp::MESSAGE_TYPE_TLV)
      end

      def server_identifier
        get_tlv_field(Dhcp::SERVER_IDENTIFIER_TLV)
      end

      def client_identifier
        get_tlv_field(Dhcp::CLIENT_IDENTIFIER_TLV)
      end
````
これが今後要望などあると、追加するためのメソッドとともに増えてくるので、
行数と修正にかかる時間、デグレーションを減らしたい考えです。いい方法などあれば教えてください。

2014/06/24
以下のようにして自動生成するようにした
````ruby
      def method_missing(method)
        tlv_methods = Dhcp::Constants.constants(true).map do |const|
          const.downcase
        end
        if dhcp.methods.include?(method)
          dhcp.send(method)
        elsif tlv_methods.include?(method)
          send :get_tlv_field, Dhcp::Constants.const_get(method.upcase)
        end
      end

      def get_tlv(tlv_type)
        tlv = dhcp.optional_tlvs.find do | each |
          each['tlv_type'] == tlv_type
        end
        tlv['tlv_value'] if tlv
      end

      def get_tlv_field(tlv_type)
        tlv = get_tlv(tlv_type)
        tlv.snapshot if tlv
      end
````

**Comment by shun159** [comment]
#78 を取り消して、改めて出し直して良いでしょうか？
※houndからのコメントが1k超えてて閲覧できないので。

**Comment by yasuhito** [comment]
はい、どうぞ!

**Comment by shun159** [comment]
#78　閉じました。
